# Site settings
email: "sagelt@gmail.com"
baseurl: "https://svirfnebl.in"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: "UA-90873505-1"
timezone: America/Los_Angeles

# SEO settings
title: "svirfneblin"
description: "speaking to rocks about games"
url: "svirfnebl.in"
twitter_username: "olde_fortran"
default_img: "/images/sage.jpg"

# Profile settings
name: "sage latorra"
profile_img: "/images/sage.jpg"
profile: "Sage LaTorra is a game designer and senior engineering manager at Google. You may know him from Dungeon World."
social:
  github: "https://github.com/Sagelt"

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - octopress-autoprefixer
