# Site settings
email: "sagelt@gmail.com"
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: "UA-90873505-1"

# SEO settings
title: "svirfneblin"
description: "speaking to rocks"
url: "svirfnebl.in"
twitter_username: "olde_fortran"
default_img: "/images/sage.jpg"

# Profile settings
name: "sage latorra"
profile_img: "/images/sage.jpg"
profile: "Sage LaTorra is a game designer and senior test engineer at Google. You may know him from Dungeon World."
social:
  google-plus: "https://plus.google.com/+SageLaTorra"
  twitter: "https://twitter.com/olde_fortran"
  podcast: "http://www.anotherquestion.com/"
  github: "https://github.com/Sagelt"

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
